repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=8192]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: check-toml
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy .
      language: system
      types: [python]
      verbose: true
      pass_filenames: false
